name: Build and Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.6"

      - name: Build
        run: go build -v -o todoman-linux todoman.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: todoman-linux
          path: todoman-linux

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.6"

      - name: Build
        run: go build -v -o todoman-macos todoman.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: todoman-macos
          path: todoman-macos

  create-release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-macos]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux Artifact
        uses: actions/download-artifact@v3
        with:
          name: todoman-linux
          path: ./artifacts

      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: todoman-macos
          path: ./artifacts

      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh release create release-${{ steps.slug.outputs.sha8 }} \
            --title "Release ${{ steps.slug.outputs.sha8 }}" \
            --generate-notes \
            ./artifacts/*

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh release upload release-${{ steps.slug.outputs.sha8 }} ./artifacts/* --clobber
